---
# tasks file for xps13-ubuntu

- name: turn off translations, speed up apt-get update
  become: true
  lineinfile: dest=/etc/apt/apt.conf.d/99translations line='Acquire::Languages "none";' create=yes state=present backup=yes

- name: Change local repository
  become: true
  replace: dest=/etc/apt/sources.list regexp='deb http://buaya.klas.or.id' replace='deb http://kambing.ui.ac.id' backup=yes

- name: Update repository
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Installs base packages
  become: true
  action: apt name={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - jq
    - tree
    - python-pip
    - python3-pip
    - aptitude

- name: Add user to sudoers and systemd groups
  become: true
  user: name={{ lookup('env','USER') }} groups=sudo append=yes

- name: systemd groups
  become: true
  user: name={{ lookup('env','USER') }} groups=systemd-journal,systemd-network append=yes
  
- name: no password for sudo 
  become: true
  lineinfile: dest=/etc/sudoers.d/{{ lookup('env','USER') }} line="{{ lookup('env','USER') }} ALL=(ALL) NOPASSWD:ALL" create=yes state=present backup=yes 

- name: switch ctrl with capslock
  become: true
  lineinfile: dest=/etc/default/keyboard regexp='XKBOPTIONS=' line='XKBOPTIONS="ctrl:nocaps"' state=present backup=yes
  register: keyboard_file

- name: Configure keyboard
  command: dpkg-reconfigure keyboard-configuration -f noninteractive
  become: true
  when: keyboard_file.changed

- name: Change the font to more readable size 
  become: true
  copy: src=console-setup dest=/etc/default/console-setup owner=root group=root mode=0644 backup=yes
  register: console_file

- name: Reconfigure console 
  command: dpkg-reconfigure console-setup -f noninteractive
  become: true
  when: console_file.changed

# Install neovim

- name: add repository for neovim
  become: true
  apt_repository: repo='ppa:neovim-ppa/unstable' state=present update_cache=yes

- name: Install neovim
  become: true
  apt: name=neovim state=present

- name: Update the vi link to nvim
  become: true
  alternatives: name={{ item.name }} link={{ item.link }} path=/usr/bin/nvim
  with_items:
    - { link: '/usr/bin/vi', name: 'vi' }
    - { link: '/usr/bin/vim', name: 'vim' }
    - { link: '/usr/bin/editor', name: 'editor' }
