---
# tasks file for xps13-ubuntu

- name: turn off translations, speed up apt-get update
  become: true
  lineinfile: dest=/etc/apt/apt.conf.d/99translations line='Acquire::Languages "none";' create=yes state=present backup=yes

- name: Change local repository
  become: true
  replace: dest=/etc/apt/sources.list regexp='deb http://buaya.klas.or.id' replace='deb http://kambing.ui.ac.id' backup=yes

- name: Update repository
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Installs base packages
  become: true
  action: apt name={{ item }} state=present install_recommends=no update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - jq
    - tree
    - python-pip
    - python3-pip
    - aptitude

- name: Add user to sudoers and systemd groups
  become: true
  user: name={{ lookup('env','USER') }} groups=sudo append=yes

- name: systemd groups
  become: true
  user: name={{ lookup('env','USER') }} groups=systemd-journal,systemd-network append=yes
  
- name: no password for sudo 
  become: true
  lineinfile: dest=/etc/sudoers.d/{{ lookup('env','USER') }} line="{{ lookup('env','USER') }} ALL=(ALL) NOPASSWD:ALL" create=yes state=present backup=yes 

- name: switch ctrl with capslock
  become: true
  lineinfile: dest=/etc/default/keyboard regexp='XKBOPTIONS=' line='XKBOPTIONS="ctrl:nocaps"' state=present backup=yes
  register: keyboard_file

- name: Configure keyboard
  command: dpkg-reconfigure keyboard-configuration -f noninteractive
  become: true
  when: keyboard_file.changed

- name: Change the font to more readable size 
  become: true
  copy: src=console-setup dest=/etc/default/console-setup owner=root group=root mode=0644 backup=yes
  register: console_file

- name: Reconfigure console 
  command: dpkg-reconfigure console-setup -f noninteractive
  become: true
  when: console_file.changed

# Install neovim

- name: add repository for neovim
  become: true
  apt_repository: repo='ppa:neovim-ppa/unstable' state=present update_cache=yes

- name: Install neovim
  become: true
  apt: name=neovim state=present

- name: Update the vi link to nvim
  become: true
  alternatives: name={{ item.name }} link={{ item.link }} path=/usr/bin/nvim
  with_items:
    - { link: '/usr/bin/vi', name: 'vi' }
    - { link: '/usr/bin/vim', name: 'vim' }
    - { link: '/usr/bin/editor', name: 'editor' }

- name: File globs
  file: src={{ item }} dest={{ ansible_env.HOME }}/{{ item | basename }} state=link        
  with_fileglob:
    - .*

- name: Check if bluetooth firmware is loaded
  shell: " /bin/dmesg | /bin/egrep -q 'BCM20702A1-0a5c-216f.hcd failed'"
  register: result
  ignore_errors: True

- name: Get the cab file
  get_url: url=http://download.windowsupdate.com/d/msdownload/update/driver/drvs/2014/07/20662520_6c535fbfa9dca0d07ab069e8918896086e2af0a7.cab dest=/tmp/20662520_6c535fbfa9dca0d07ab069e8918896086e2af0a7.cab
  when: result|failed

- name: Install cabextract
  become: true
  apt: name=cabextract state=present
  when: result|failed

- name: Checkout hex2hcd repo 
  git: repo=https://github.com/jessesung/hex2hcd.git dest=/tmp/hex2hcd
  when: result|failed

- name: Make hex2hcd
  make: chdir=/tmp/hex2hcd
  when: result|failed

- name: Extracting cab file
  shell: "cd /tmp/hex2hcd && cabextract ../20662520_6c535fbfa9dca0d07ab069e8918896086e2af0a7.cab"
  when: result|failed

- name: Extract hcd file
  shell: "cd /tmp/hex2hcd && ./hex2hcd BCM20702A1_001.002.014.1443.1572.hex ../BCM20702A1-0a5c-216f.hcd"
  when: result|failed

- name: Msg to reboot 
  debug: msg="Need to reboot to include this bluetooth firmware"
  when: result|failed
